# Generated by Django 6.1.1 on 2026-10-05 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_profesor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('B', 'Baja')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(help_text='Id de la carrera', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='numero_empleado',
            field=models.CharField(help_text='Identificador del docente', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CONTROL_ESCOLAR', 'Control escolar'), ('COORDINADOR', 'Coordinador'), ('PROFESOR', 'Profesor'), ('ALUMNO', 'Alumno')], max_length=20)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
