# Generated by Django 6.1.1 on 2026-10-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_profesor_estatus_alter_carrera_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Para borrado lógico'),
        ),
    ]
